consenlabs/tokenlon-contracts

- contracts/test/forkMainnet/RewardDistributor.t.sol
- contracts/test/mocks/MockContract.sol
- contracts/test/utils/BalanceUtil.sol
> Add RewardDistributor tests

- contracts/test/AllowanceTarget.t.sol
- contracts/test/LON.t.sol
Add test for `AllowanceTarget`.
> Add allowance target test

- contracts/test/AllowanceTarget.t.sol
- contracts/test/LON.t.sol
- contracts/test/LONStaking.t.sol
- contracts/test/RFQ.t.sol
- contracts/test/Spender.t.sol
- contracts/test/UserProxy.t.sol
- contracts/test/forkMainnet/AMMWrapper.t.sol
- contracts/test/forkMainnet/LimitOrder.t.sol
- contracts/test/forkMainnet/RewardDistributor.t.sol
- contracts/test/utils/BalanceUtil.sol
- contracts/test/utils/StrategySharedSetup.sol
Turns out there's already `deal` function to set ERC20 balance in `forge-std` lib
> Use deal function to set ETH/ERC20 balance

- contracts/test/Spender.t.sol
- contracts/test/utils/StrategySharedSetup.sol
- Add Spender tests for Deflationary token, NoReturn token and NoRevert token
> Add Spender tests for non standard ERC20 tokens

- contracts/AMMWrapper.sol
- contracts/AMMWrapperWithPath.sol
- contracts/interfaces/IAMMWrapper.sol
- contracts/interfaces/IAMMWrapperWithPath.sol
- contracts/test/forkMainnet/AMMWrapper.t.sol
- contracts/test/forkMainnet/AMMWrapperWithPath.t.sol
- contracts/utils/LibConstant.sol
- Remove version constant
- Add license
- Integrate LibConstant
- Set Uniswap & Sushiswap address in constructor
- Refine interfaces
> Refactor AMMWrapper

- contracts/test/RFQ.t.sol
- contracts/test/forkMainnet/LimitOrder.t.sol
- contracts/test/mocks/MockERC1271Wallet.sol
- test/pmm.ts
- Verify sig in `MockERC1271Wallet` so we can know at least if our signing utils in tests are correct
> Verify sig in MockERC1271Wallet

- contracts/interfaces/IveLON.sol
- contracts/veLON.sol
Add basic functions like `deposit` and `withdraw` of veLON with `_checkpoint()` calculation.
> add basic functions of veLON

- contracts/interfaces/IveLON.sol
- contracts/veLON.sol
- Add vBalance view function for user
- Add total vBalance view function for pool global
- Add `ownershipChange` to prevent flash NFT
- Override NFT `_transfer` function to set `ownershipChange` first
> Add vBalance and supply view functions

- contracts/test/veLON/Deposit.t.sol
- contracts/test/veLON/Withdraw.t.sol
- contracts/test/veLON/vBalance.t.sol
- contracts/veLON.sol
- fix  cannot  get `totalvBalanceAtTime()` in future
- add test for each vBalance and totalVBalance
- add event assertion test for Withdraw()
> Add test for vBalance function

- contracts/LimitOrder.sol
- contracts/interfaces/ILimitOrder.sol
- contracts/test/forkMainnet/LimitOrder.t.sol
Remove profit cap and in fillByProtocol case.
> remove profit cap of limit order

- contracts/interfaces/IveLON.sol
- contracts/test/veLON/Deposit.t.sol
- contracts/test/veLON/Withdraw.t.sol
- contracts/veLON.sol
- add Supply event
- add test for supply event
> Add velon supply event

- contracts/test/LONStaking.t.sol
- contracts/test/veLON/Convert.t.sol
- contracts/test/veLON/Deposit.t.sol
- contracts/test/veLON/Setup.t.sol
- contracts/test/veLON/Withdraw.t.sol
- contracts/test/veLON/vBalance.t.sol
- contracts/veLON.sol
- Fix epoch assignment when updating points
- Check epoch index in tests
- Refactoring
> Fix veLON epoch index and refactor

- contracts/PermanentStorage.sol
- contracts/interfaces/IPermanentStorage.sol
- contracts/test/PermanentStorage.t.sol
- Remove PMM related parts
- Refactoring
> refactor PermanentStorage

- .github/workflows/node.js.yml
- contracts/test/LONStaking.t.sol
- contracts/test/veLON/Convert.t.sol
- contracts/test/veLON/vBalance.t.sol
- contracts/veLON.sol
- package.json
- fix vBalanceOfAtTime when target time is before lastPoint
- fix totalVBalanceAtTime target time is before lastPoint
- add more test cases for vBalance and totalVBalance
> Fix velon vbalance of at time

- contracts/test/PermanentStorage.t.sol
- contracts/test/RFQ.t.sol
- contracts/test/Spender.t.sol
- contracts/test/TreasuryVester.t.sol
- contracts/test/UserProxy.t.sol
- contracts/test/forkMainnet/AMMQuoter.t.sol
- contracts/test/forkMainnet/AMMWrapper/Setup.t.sol
- contracts/test/forkMainnet/AMMWrapperWithPath/Setup.t.sol
- contracts/test/forkMainnet/LimitOrder.t.sol
- contracts/test/forkMainnet/RewardDistributor.t.sol
- contracts/test/mocks/MockDeflationaryERC20.sol
- contracts/test/mocks/MockERC1271Wallet.sol
- contracts/test/mocks/MockERC20.sol
- contracts/test/mocks/MockNoReturnERC20.sol
- contracts/test/mocks/MockNoRevertERC20.sol
- contracts/test/mocks/MockStrategy.sol
- contracts/test/mocks/MockWETH.sol
- contracts/test/utils/AMMUtil.sol
- contracts/test/utils/Addresses.sol
- contracts/test/utils/BalanceSnapshot.sol
- contracts/test/utils/BalanceUtil.sol
- contracts/test/utils/RegisterCurveIndexes.sol
- contracts/test/utils/StrategySharedSetup.sol
- contracts/test/utils/SushiswapUtil.sol
- contracts/test/utils/UniswapV3Util.sol
Eliminate compiler waring of testing files.
- Add licenses
- Strict mutability
- Adjust solc pragma
> Remove test file compiler warning

- contracts/Spender.sol
- contracts/interfaces/ISpender.sol
- contracts/test/Spender.t.sol
- contracts/utils/Ownable.sol
- Share `Ownable.sol`
- Move events in interface
> Refactor spender

- contracts/AMMWrapper.sol
- contracts/AMMWrapperWithPath.sol
- contracts/test/forkMainnet/AMMWrapperWithPath/Setup.t.sol
- contracts/test/forkMainnet/AMMWrapperWithPath/TradeBalancerV2.t.sol
- contracts/test/forkMainnet/AMMWrapperWithPath/TradeCurveV2.t.sol
- contracts/test/forkMainnet/AMMWrapperWithPath/TradeUniswapV3.t.sol
- contracts/test/utils/RegisterCurveIndexes.sol
- integrate` curveV2` and `balancerV2` into `AMMWrapperWithPath` in public repo 
- integrate and adjust some setups in test cases (most of the test cases are directly copy and paste from private repo)
> Integrate curve v2 and balance v2

- contracts/AMMWrapper.sol
- contracts/AMMWrapperWithPath.sol
- contracts/L2Deposit.sol
- contracts/LimitOrder.sol
- contracts/RFQ.sol
- contracts/interfaces/IAMMWrapper.sol
- contracts/interfaces/IL2Deposit.sol
- contracts/interfaces/ILimitOrder.sol
- contracts/interfaces/IRFQ.sol
- contracts/interfaces/ISetAllowance.sol
- contracts/interfaces/IStrategyBase.sol
- contracts/test/RFQ.t.sol
- contracts/test/forkMainnet/AMMWrapper/Allowance.t.sol
- contracts/test/forkMainnet/AMMWrapper/DepositETH.t.sol
- contracts/test/forkMainnet/AMMWrapper/SetFeeCollector.t.sol
- contracts/test/forkMainnet/AMMWrapper/Setup.t.sol
- contracts/test/forkMainnet/AMMWrapper/SetupTest.t.sol
- contracts/test/forkMainnet/AMMWrapper/UpgradeSpender.t.sol
- contracts/test/forkMainnet/AMMWrapperWithPath/Setup.t.sol
- contracts/test/forkMainnet/AMMWrapperWithPath/SetupTest.t.sol
- contracts/test/forkMainnet/L2Deposit/Setup.t.sol
- contracts/test/forkMainnet/LimitOrder.t.sol
- contracts/test/mocks/MockERC1271Wallet.sol
- contracts/test/utils/StrategySharedSetup.sol
- contracts/utils/StrategyBase.sol
Based on branch `add-l2-deposit-contract-new-based`.
The StrategyBase contract covers following basic aspects:
- Ownership management
- `spender` management
- Token allowance and WETH deposit (mainly for emergency purpose)
- onlyUserProxy() modifier
- `permStorage` address
> Add strategy base contract

- contracts/L2Deposit.sol
- contracts/interfaces/IL2Deposit.sol
Add natspec to L2Deposit.sol and IL2Deposit.sol
> Add natspec for l2deposit

- contracts/AMMWrapper.sol
- contracts/AMMWrapperWithPath.sol
- contracts/RFQ.sol
- contracts/interfaces/IAMMWrapper.sol
- contracts/interfaces/IAMMWrapperWithPath.sol
- contracts/interfaces/IRFQ.sol
> Add natspec for AMM

- contracts/L2Deposit.sol
- contracts/test/forkMainnet/L2Deposit/Deposit.t.sol
- contracts/test/forkMainnet/L2Deposit/Setup.t.sol
- contracts/utils/L2DepositLibEIP712.sol
- contracts/utils/LimitOrderLibEIP712.sol
- doc/strategies/L2Deposit.md
According to the found in #125 .
> Adjust l2deposit arbitrum refund addr

- .prettierignore
- foundry.toml
Update
- foundry config
- prettier ignore config
> Update foundry and prettier ignore configs

- contracts/LimitOrder.sol
- contracts/test/forkMainnet/LimitOrder.t.sol
Check `profitRecipient` and `recipient`.
> Add zero address check to LimitOrder

- contracts/LimitOrder.sol
Check zero token amount in `_quoteOrder()`
> Add LimitOrder sanity checks

- contracts/UserProxy.sol
Check bool directly to save gas.
> Refactor bool equality check in UserProxy

- contracts/LimitOrder.sol
- contracts/PermanentStorage.sol
- contracts/utils/Multicall.sol
Ref : https://github.com/byterocket/c4-common-issues/blob/main/0-Gas-Optimizations.md/#g012---use-prefix-increment-instead-of-postfix-increment-if-possible
> Optimize for loop with pre increment

- contracts/LimitOrder.sol
Add memory cache for `spender` and `feeCollector` vars.
> Cache LimitOrder storage var

- contracts/LimitOrder.sol
- contracts/PermanentStorage.sol
- contracts/UserProxy.sol
- contracts/interfaces/ILimitOrder.sol
- contracts/test/forkMainnet/LimitOrder.t.sol
Applies to
- contracts/PermanentStorage.sol
- contracts/LimitOrder.sol
- contracts/UserProxy.sol
> Apply two-step owership changing flow

- doc/README.md
> Fix: typos

- contracts/AMMQuoter.sol
- contracts/AMMWrapperWithPath.sol
- contracts/LimitOrder.sol
- contracts/MarketMakerProxy.sol
- contracts/MerkleRedeem.sol
- contracts/PermanentStorage.sol
- contracts/RewardDistributor.sol
- contracts/Spender.sol
- contracts/SpenderSimulation.sol
- contracts/utils/MerkleProof.sol
- contracts/utils/Multicall.sol
- contracts/utils/StrategyBase.sol
- test/forkMainnet/LimitOrder.t.sol
The gas usage diff from cache storage variables, diff generated by `forge snapshot --diff`.
> Apply latest audit changes

- test/RFQ.t.sol
- test/forkMainnet/AMMWrapper/Signing.t.sol
- test/forkMainnet/L2Deposit/Signing.t.sol
- test/forkMainnet/LimitOrder.t.sol
- test/utils/Addresses.sol
Fix the json path format. Ref https://crates.io/crates/jsonpath-rust.
> Fix CI build

- .github/workflows/gas-diff.yml
Fix node version in gas diff workflow, check the cause here
https://github.com/consenlabs/tokenlon-contracts/actions/runs/4221251627/jobs/7328323506
> Fix node version in gas diff workflow

- contracts/interfaces/IStrategy.sol
Check #169 for the example of strategy contract.
> Add v6 IStrategy

- contracts/abstracts/TokenCollector.sol
- contracts/interfaces/IUniswapPermit2.sol
- test/forkMainnet/TokenCollector.t.sol
Add permit2 signature transfer support in TokenCollector
> [v6] Support permit2 signature transfer in TokenCollector

- contracts/RFQ.sol
- contracts/interfaces/IRFQ.sol
- test/forkMainnet/RFQ.t.sol
Allow user brining feeFactor as a param to contract.
> RFQ feeFactor as a param

- contracts/AMMStrategy.sol
- contracts/SmartOrderStrategy.sol
- contracts/interfaces/ISmartOrderStrategy.sol
- test/forkMainnet/SmartOrderStrategy.t.sol
This strategy contract allows bringing input ratio and replace the amount during execution.
> Implement smart order strategy

- contracts/UniAgent.sol
- contracts/interfaces/IUniAgent.sol
- contracts/interfaces/IUniswapRouterV2.sol
- contracts/interfaces/IUniswapUniversalRouter.sol
- test/forkMainnet/UniAgent/Setup.t.sol
- test/forkMainnet/UniAgent/Universal.t.sol
- test/forkMainnet/UniAgent/V2.t.sol
- test/forkMainnet/UniAgent/V3.t.sol
After several tests of different versions, I found that it's not worthy to have the relayed design in here. From the gas efficiency perspective, the relayed one cost similar as GS does so no need to have another similar implementation. However, the self-submit way could perform much closer as user directly call the uniswap official router.
> Implement UniAgent contract

- contracts/UniAgent.sol
- contracts/interfaces/IUniAgent.sol
- test/forkMainnet/UniAgent/Setup.t.sol
Token will be transferred to `UniversalRouter` directly so no need to approve.
> Refactor UniAgent and add NatSpec

- contracts/interfaces/ICurveFiV2.sol
- test/forkMainnet/SmartOrderStrategy/AMMs.t.sol
- test/forkMainnet/SmartOrderStrategy/IntegrationV6.t.sol
- test/forkMainnet/SmartOrderStrategy/Setup.t.sol
- test/forkMainnet/SmartOrderStrategy/Validation.t.sol
Added some cases
- WETH unwrap handling
- multiple AMMs
- with V6 RFQ
- with V6 LimitOrderSwap
> add more SmartOrderStrategy test cases

- README.md
- Update the readme file for v5.3.3 release
> update readme for v5.3.3 release

- financial-statements/2024_Q2.csv
- Upload the Q2 financial statements
> upload the Q2 financial statements

- financial-statements/2024_Q4.csv
- Upload 2024 Q4 financial statements
> upload the Q4 financial statements

- financial-statements/2025_Q1.csv
- Upload the 2025 Q1 financial statements
> upload the 2025 Q1 financial statements
