consenlabs/tokenlon-contracts

contracts/PermanentStorage.sol
contracts/UserProxy.sol
contracts/test/PermanentStorage.t.sol
contracts/test/UserProxy.t.sol
contracts/test/utils/StrategySharedSetup.sol

~According to Tokenlon contract version control policy, remove version stored in contract. Protect `initialize` function being called twice using `Initializable` contract from OZ. Set operator in `initialize` function.~
Adjust init function for new network deployment. May change design in the future.

Adjust init function for new network

---

contracts/test/RFQ.t.sol
contracts/test/forkMainnet/AMMWrapper.t.sol
contracts/test/forkMainnet/AMMWrapperWithPath.t.sol
contracts/test/forkMainnet/LimitOrder.t.sol
contracts/utils/SignatureValidator.sol

- Allow sig length 65 in EIP712/EthSign sig type in SignatureValidator
- Update tests to use new signing method (sig length 65)
- Add test for old signing method (sig length 97)

Update signature validator sig length check

---

contracts/test/AllowanceTarget/CompleteSetSpender.t.sol
contracts/test/AllowanceTarget/Constructor.t.sol
contracts/test/AllowanceTarget/ExecuteCall.t.sol
contracts/test/AllowanceTarget/SetSpenderWithTimelock.t.sol
contracts/test/AllowanceTarget/Setup.t.sol
contracts/test/AllowanceTarget/Teardown.t.sol

In order to make the AllowanceTarget contract test files more readable, change these test files into a hierarchical directory.
These test contracts conform to the following specifications:
1) One file, one contract.
2) Test contracts are named with upper camel case.
3) Test functions are named with lower camel case.
4) Minimal import principle: do not import unused libraries.
Please use the following command to test:
```bash
forge test -vvv --force --match-path 'contracts/test/AllowanceTarget/*.t.sol'
```
The following is the test execution result:
```
Running 2 tests for contracts/test/AllowanceTarget/Constructor.t.sol:TestAllowanceTargetConstructor
[PASS] testCannotDeployByZeroAddress() (gas: 41031)
[PASS] testConstructor() (gas: 7650)
Test result: ok. 2 passed; 0 failed; finished in …
```

Redefine Foundry test for AllowanceTarget contract

---

contracts/RFQ.sol
contracts/interfaces/IWeth.sol
contracts/test/RFQ.t.sol

- Add `feeCollector`
- Operator can set `feeCollector`
- Transfer fee to `feeCollector` in RFQ contract

Transfer fee to fee collector in RFQ

---

contracts/interfaces/IveLON.sol
contracts/veLON.sol

Separate user and global updating functions so no need to determine whether `tokenId == 0` in multiple places.
- bias -> vBalance
- slope -> decliningRate

Separate veLon checking function and rename fields

---

contracts/UserProxy.sol
contracts/test/UserProxy.t.sol
contracts/utils/Multicall.sol

If one of subcall is reverted during multicall process, the `result` offset will be changed in order to get the revert message. Therefore, copying the `success` and `result` into array should be done before changing the offset.

fix multicall result data

---

contracts/AMMWrapper.sol
contracts/AMMWrapperWithPath.sol
contracts/test/forkMainnet/AMMWrapper/CollectFee.t.sol
contracts/test/forkMainnet/AMMWrapper/Setup.t.sol
contracts/test/forkMainnet/AMMWrapper/TradeCurveV1.t.sol
contracts/test/forkMainnet/AMMWrapper/TradeSushiswap.t.sol
contracts/test/forkMainnet/AMMWrapper/TradeUniswapV2.t.sol
contracts/test/forkMainnet/AMMWrapperWithPath/TradeBalancerV2.t.sol
contracts/test/forkMainnet/AMMWrapperWithPath/TradeCurveV1.t.sol
contracts/test/forkMainnet/AMMWrapperWithPath/TradeCurveV2.t.sol
contracts/test/forkMainnet/AMMWrapperWithPath/TradeSushiswap.t.sol
contracts/test/forkMainnet/AMMWrapperWithPath/TradeUniswapV3.t.sol

Since the actual amount that user will receive is `outupt * (1 - feeRate)`, so the `minAmountOut` should be calculated as `order.makerAssetAmount * (1 / 1 - feeRate)`.
- Keep default fee factor in most cases instead of 0
- Assert balance change precisely (replace `assertChangeGt` with `assertChange`)
- Lower default fee factor in `AMMWrapper` tests so the order rate is much more straightforward
WIP
- The Curve v1 quote returned by AMMQuoter is different from the result of swapping, still debugging.

Adjust AMM actual fee calculation

---

contracts/test/PermanentStorage.t.sol
contracts/test/RFQ.t.sol
contracts/test/Spender.t.sol
contracts/test/TreasuryVester.t.sol
contracts/test/forkMainnet/AMMWrapperWithPath/TradeUniswapV3.t.sol
contracts/test/forkMainnet/RewardDistributor.t.sol
foundry.toml

- After overviewing the whole tokenlon contracts testing, I turn the all event unit testing to emitting strictly. Namely, the event testing must be `expectEmit(true,  true, true, true)`.
- Related Internal documentation: **Strictly Event Emitting Unit Testing in Tokenlon**

strictly event emitted

---

.github/workflows/node.js.yml
README.md
package.json

```shell
~ % git clone git@github.com:consenlabs/tokenlon-contracts.git
~ % cd tokenlon-contracts && yarn run setup && yarn run compile
tokenlon-contracts % MAINNET_NODE_RPC_URL="https://eth-mainnet.g.alchemy.com/v2/<Your API Key from https://dashboard.alchemy.com/ website>"
tokenlon-contracts % yarn run test-foundry-fork
```

spec: update fork_block_number of readme.md

---

.github/workflows/node.js.yml
package.json

Add default env value in `package.json` so no need to set env variable before running normal tests.

add default env value for tests

---

contracts/RFQ.sol
contracts/test/RFQ.t.sol
contracts/test/Spender.t.sol
contracts/utils/SpenderLibEIP712.sol

1. To prevent the signature from being used by another transaction in the same strategy contract, the spendWithPermit must contain the hash of the transaction or order the user wants to execute.
2. Replace txHash in spendWithPermit with actionHash since actionHash will not be confused with blockchain's txHash.
3. The value of actionHash is the hash of the transaction, order or deposit hash calculated in each (AMM, RFQ, L2Deposit, LimitOrder, etc.) strategy contract.
4. Verify command:
```shell
tokenlon-contracts % DEPLOYED=false forge test -vvv --match-path 'contracts/test/Spender.t.sol'
tokenlon-contracts % DEPLOYED=false forge test -vvv --match-path 'contracts/test/RFQ.t.sol'
```
<details>
<summary>Output: (Please click here to expand)</summary>
<pre><code>
tokenlon-contracts % …

feat: spendWithPermit should contain transaction or order hash

---

contracts/RFQ.sol
contracts/Spender.sol
contracts/SpenderSimulation.sol
contracts/test/RFQ.t.sol

RFQ, Spender contracts and their Foundry test contract changed to non named parameter type.
1. RFQ, Spender contracts and their Foundry test contract changed to non named parameter type.
2. Verify command (Not necessary):
```shell
tokenlon-contracts % DEPLOYED=false forge test -vvv --match-path 'contracts/test/Spender.t.sol'
tokenlon-contracts % DEPLOYED=false forge test -vvv --match-path 'contracts/test/RFQ.t.sol'
```

refac: rfq, spender contracts changed to non named parameter type

---

contracts/test/RFQ.t.sol
contracts/test/Spender.t.sol
contracts/test/utils/Permit.sol

1. Centralize the signSpendWithPermit function into Permit.sol to reduce the amount of code.
2. Currently only the RFQ.t.sol and Spender.t.sol files are modified.
3. Verify command:
```shell
tokenlon-contracts % DEPLOYED=false forge test -vvv --match-path 'contracts/test/Spender.t.sol'
tokenlon-contracts % DEPLOYED=false forge test -vvv --match-path 'contracts/test/RFQ.t.sol'
```

refac: move the signSpendWithPermit function in foundry test

---

contracts/AMMWrapper.sol
contracts/AMMWrapperWithPath.sol
contracts/interfaces/IAMMWrapper.sol
contracts/interfaces/IAMMWrapperWithPath.sol
contracts/test/forkMainnet/AMMWrapper/CollectFee.t.sol
contracts/test/forkMainnet/AMMWrapper/Setup.t.sol
contracts/test/forkMainnet/AMMWrapper/TradeCurveV1.t.sol
contracts/test/forkMainnet/AMMWrapper/TradeSushiswap.t.sol
contracts/test/forkMainnet/AMMWrapper/TradeUniswapV2.t.sol
contracts/test/forkMainnet/AMMWrapperWithPath/Setup.t.sol
contracts/test/forkMainnet/AMMWrapperWithPath/TradeBalancerV2.t.sol
contracts/test/forkMainnet/AMMWrapperWithPath/TradeCurveV1.t.sol
contracts/test/forkMainnet/AMMWrapperWithPath/TradeCurveV2.t.sol
contracts/test/forkMainnet/AMMWrapperWithPath/TradeSushiswap.t.sol
contracts/test/forkMainnet/AMMWrapperWithPath/TradeUniswapV3.t.sol

1. Remove spendFromUser and spendFromUserTo func.
2. Reduce parameters of trade() function to avoid stack too deep error.
3. Add the takerAssetPermitSig parameter of the trade() function to authenticate the spendFromUserToWithPermit function.
4. Because AMMWrapper and AMMWrapperWithPath use the same _prepare() function, they need to be modified together.
5. Modify Foundry tests for AMMWrapper and AMMWrapperWithPath to use trade() function with takerAssetPermitSig parameter.
6. In Foundry tests, use curly braces to avoid stack too deep error.
7. Verify command:
```shell
tokenlon-contracts % MAINNET_NODE_RPC_URL="https://eth-mainnet.g.alchemy.com/v2/<YOUR API KEY>"
tokenlon-contracts % DEPLOYED=false forge test -vvv --fork-url ${MAINNET_NODE_RPC_URL} --fork-block-number '15451000' …
```

Amm with spender permit

---

contracts/utils/SignatureValidator.sol

The `ERC1271_FALLBACK_MAGICVALUE_BYTES32` is not used in any place.

remove unused const in SignatureValidator.sol

---

.github/workflows/tokenlon-contracts.yml

The caching step has been merged into foundry-toolchain: https://github.com/foundry-rs/foundry-toolchain/releases/tag/v1.0.8

Remove foundry CI cache step

---

contracts/LimitOrder.sol
contracts/test/forkMainnet/LimitOrder.t.sol

Introduce two-step fee factor updating process to LimitOrder contract. If the operator set feeFactor to 100% or some unacceptable percentage, user can cancel their orders within the timelock period.

Limitorder two-step set fee factors

---

contracts/Spender.sol
contracts/interfaces/ISpender.sol
contracts/test/Spender.t.sol

1. The spendFromUser() function in the Spender.sol contract was replaced by the new spendFromUserToWithPermit() function, so the spendFromUser() was removed and the associated Foundry Test was also removed.
2. Verify command:
```shell
DEPLOYED=false forge test -vvv --match-path 'contracts/test/Spender.t.sol'
```

feat: remove spendFromUser() func in Spender.sol

---

test/utils/BalanceUtil.sol

Approach 1 (48edaee). `setERC20Balance` update `totalSupply` in local, not in fork
Approach 2 (85af8fa). try catch if `totalSupply` can be update regardless of fork

`BalanceUtil` not inherit `Addresses`

---

contracts/utils/Offer.sol
test/forkMainnet/RFQv2.t.sol

The field `minMakerTokenAmount` is not used in v5.

remove minMakerTokenAmount in offer

---

contracts/utils/Asset.sol
test/forkMainnet/RFQv2.t.sol

After discussion, the `feeColeector` of RFQv2 should be itself until the whole buyback design is updated. So the fee transfer can be skip if `to` is itself.

RFQv2 skip transfer if to address is this

---

.github/workflows/gas-diff.yml
contracts/RFQ.sol
contracts/abstracts/TokenCollector.sol
test/forkMainnet/GenericSwap.t.sol
test/forkMainnet/LimitOrderSwap/Setup.t.sol
test/forkMainnet/RFQ.t.sol
test/forkMainnet/TokenCollector.t.sol
test/forkMainnet/UniAgent/Setup.t.sol

~To shorten the data for token collector, add `length == 1` condition for basic token source type.~
Use bytes concat for permit data wrapping. First it's easier to detect the type of source without abi decoding, and second it saves some length of data.

Refactor token collector

---

contracts/RFQ.sol
contracts/interfaces/IRFQ.sol
test/forkMainnet/RFQ.t.sol

Consider the partial fill case, emit with actual settle amount instead of original amount in the order.

adjust RFQ event amount fields

---

contracts/abstracts/TokenCollector.sol
contracts/interfaces/IUniswapPermit2.sol
test/forkMainnet/GenericSwap.t.sol
test/forkMainnet/LimitOrderSwap/CoordinatedTaker.t.sol
test/forkMainnet/LimitOrderSwap/Fill.t.sol
test/forkMainnet/LimitOrderSwap/FullOrKill.t.sol
test/forkMainnet/LimitOrderSwap/GroupFill.t.sol
test/forkMainnet/LimitOrderSwap/Setup.t.sol
test/forkMainnet/RFQ.t.sol
test/forkMainnet/TokenCollector.t.sol
test/forkMainnet/UniAgent/Setup.t.sol
test/forkMainnet/UniAgent/V2.t.sol
test/utils/Permit2Helper.sol

The `AllowanceTrasfer` should be called with max(uint160) as amount so it can be done just once. It's not equal to say that we enforce user to set the allowance to max. A user can call `Permit2` contract directly to setup whatever amount they want before swap. But in `TokenCollector`, it works like a bundled call so I think `max(uint160)` should be suitable for most cases.

fix token collector permit2 logic and test

---

contracts/UniAgent.sol
contracts/abstracts/AdminManagement.sol

Cache array length in `fillLimitOrderGroup` function of LimitOrderSwap contract will cause stack overflow. Considered it save just a little gas, keep it unchanged now.

cache array length

---

contracts/UniAgent.sol
contracts/abstracts/AdminManagement.sol

Caching array length of a calldata array actually increase the gas consumption instead. Revert the previous change.

Revert "cache array length"

---

contracts/RFQ.sol
test/forkMainnet/RFQ.t.sol

First commit on add maker WETH option.

add WETH option design for maker

---

contracts/GenericSwap.sol
contracts/SmartOrderStrategy.sol
contracts/libraries/GenericSwapData.sol
test/forkMainnet/GenericSwap.t.sol
test/forkMainnet/SmartOrderStrategy/AMMs.t.sol
test/forkMainnet/SmartOrderStrategy/IntegrationV6.t.sol
test/forkMainnet/SmartOrderStrategy/Setup.t.sol

For gas optimization purposes, we retain 1 wei of each token in our contract(GS and SOS). This will impact the initial swap of every token, as 1 wei will be left in our contract.
- Implement the logic for leaving 1 wei in `GenericSwap.sol`
- Implement the logic for leaving 1 wei in `SmartOrderStrategy.sol`

gas optimization: leave one wei feature

---

foundry.toml

To ensure our gas diff CI reports the correct gas usage and accurately reflects the difference between two commits.
- Add `isolate = true` setting in the `foundry.toml` file. This will ensure the correct gas usage when executing `forge test` or `forge script`.
FYI: the `isolate` mode is introduced in [7186](https://github.com/foundry-rs/foundry/pull/7186)

fix: activate isolate mode in toml

---

foundry.toml

This PR sets the default EVM version (`Paris`) to `Shanghai`. The reason for this change is that all the multi-chain networks supported by Tokenlon have already adopted the `Shanghai` upgrade.

specify evm version: Shanghai
